name       : python-keras-applications
version    : 1.0.8
release    : 2
source     :
    - https://files.pythonhosted.org/packages/21/56/4bcec5a8d9503a87e58e814c4e32ac2b32c37c685672c30bc8c54c6e478a/Keras_Applications-1.0.8.tar.gz : 5579f9a12bcde9748f4a12233925a59b93b73ae6947409ff34aa2ba258189fe5
homepage   : https://keras.io/applications
license    : MIT
component  : programming.python
summary    : Reference implementations of popular deep learning models
description: |
    Keras Applications is the applications module of the Keras deep learning library. It provides model definitions and pre-trained weights for a number of popular archictures, such as VGG16, ResNet50, Xception, MobileNet, and more.
rundeps    :
    - numpy
    - python-h5py
build      : |
    %python3_setup
install    : |
    %python3_install
